; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.2 on Sat Sep 18 2021 19:40:23 GMT+0800 (Malaysia Time)
M561 ; clear any bed transform
M17 ; Re-enable stepper motors, just to be safe
G29  ; probe the bed and enable compensation