; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.2 on Sat Sep 18 2021 19:40:26 GMT+0800 (Malaysia Time)
; Wait for set temperatures to be reached
M116 P0

